Script "stack_lib_CustomControls_group_id_6437"

/*
# Name: group "searchButton" of bkgnd "searchControls" of stack "lib_CustomControls"
# ID: group id 6437 of bkgnd id 6431 of stack "lib_CustomControls"
*/


-- on mouseUp
--   if fld "searchString" is empty then
--     answer "Please enter a search string" with "OK"
--     exit to top
--   else 
--     runSearch (fld "searchString")
--   end if
-- end mouseUp
