Script "stack_lib_CustomControls_graphic_id_6487"

/*
# Name: graphic "touchTrap" of card "curtain" of stack "lib_CustomControls"
# ID: graphic id 6487 of card id 6486 of stack "lib_CustomControls"
*/


on mouseUp
   -- answer "Stop Connecting?" with "yes" or "no"
   -- trap
end mouseUp

on mouseDown
   -- trap
end mouseDown

on newGraphic
   set the rect of me to CardRect()
   set the layer of me to top   
end newGraphic
