Script "stack_color-meditation_widget_id_1032"

/*
# Name: widget "colorMedsPrefs" of group "colorSetting" of bkgnd "colorMedsToolbar" of stack "color-meditation"
# ID: widget id 1032 of group id 1176 of bkgnd id 1035 of stack "color-meditation"
# Widget Kind: com.livecode.widget.svgpath
*/


on mouseUp
     -- set the hilited of me to (not the hilited of me)
   go to card "colorPreferences"
  -- setCurrentLevel "Preferences"
end mouseUp
